platform :ios, '7.0'

pod 'DateTools'
pod 'SDWebImage'
pod 'XLForm'
pod 'AFNetworking'
pod 'CocoaLumberjack'
pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'BlocksKit'
pod 'pop'
pod 'SWTableViewCell'
pod 'MJRefresh'
pod 'MJExtension'
pod 'YTKNetwork'
pod 'Masonry'
pod 'FMDB'
pod 'Colours'
pod 'FCFileManager'
pod 'EAIntroView'
pod 'libPhoneNumber-iOS'
pod 'MWPhotoBrowser'
