# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '启动优化' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 启动优化
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'YYModel'
  pod 'SDWebImage'
  pod 'FMDB'
  pod 'fishhook'
  pod 'YYCache'
  pod 'MMKV'
  pod 'pop'
  pod 'MJRefresh'
  pod 'ChameleonFramework'
  pod 'Masonry'
end
